PRAGMA Foreign_keys = ON;

CREATE TABLE IF NOT EXISTS T_TITRE(
	TIT_CODE CHAR(8) NOT NULL,
	TIT_LIBELLE VARCHAR(32),
	PRIMARY KEY (TIT_CODE)
);

CREATE TABLE IF NOT EXISTS T_CLIENT(
	CLI_ID INT NOT NULL,
	TIT_CODE CHAR(8),
	CLI_NOM CHAR(32),
	CLI_PRENOM VARCHAR(25),
	CLI_ENSEIGNE VARCHAR(100),
	PRIMARY KEY (CLI_ID),
	FOREIGN KEY (TIT_CODE)
	REFERENCES T_TITRE(TIT_CODE)
);

CREATE TABLE IF NOT EXISTS T_EMAIL(
	EML_ID INT NOT NULL,
	CLI_ID INT,
	EML_ADRESSE VARCHAR(100),
	EML_LOCALISATION VARCHAR(64),
	PRIMARY KEY (EML_ID),
	FOREIGN KEY (CLI_ID)
	REFERENCES T_CLIENT(CLI_ID)
);

CREATE TABLE IF NOT EXISTS T_TYPE(
	TYP_CODE CHAR(8) NOT NULL,
	TYP_LIBELLE VARCHAR(32),
	PRIMARY KEY (TYP_CODE)
);

CREATE TABLE IF NOT EXISTS T_TELEPHONE(
	TEL_ID INT NOT NULL,
	CLI_ID INT,
	TYP_CODE CHAR(8),
	TEL_NUMERO CHAR(20),
	TEL_LOCALISATION VARCHAR(64),
	PRIMARY KEY (TEL_ID),
	FOREIGN KEY (CLI_ID)
	REFERENCES T_CLIENT(TEL_ID),
	FOREIGN KEY (TYP_CODE)
	REFERENCES T_TYPE(TYP_CODE)
);

CREATE TABLE IF NOT EXISTS T_ADRESSE(
	ADR_ID INT NOT NULL,
	CLI_ID INT,
	ADR_LIGNE1 VARCHAR(32),
	ADR_LIGNE2 VARCHAR(32),
	ADR_LIGNE3 VARCHAR(32),
	ADR_LIGNE4 VARCHAR(32),
	ADR_CP CHAR(5),
	ADR_VILLE CHAR(32),
	PRIMARY KEY (ADR_ID),
	FOREIGN KEY (CLI_ID)
	REFERENCES T_CLIENT(CLI_ID)
);

CREATE TABLE IF NOT EXISTS T_MODE(
	PMT_CODE CHAR(8) NOT NULL,
	PMT_LIBELLE VARCHAR(64),
	PRIMARY KEY (PMT_CODE)
);

CREATE TABLE IF NOT EXISTS T_FACTURE(
	FAC_ID INT NOT NULL,
	CLI_ID INT,
	PMT_CODE CHAR(8),
	FAC_DATE DATE,
	FAC_PMT_DATE DATE,
	PRIMARY KEY (FAC_ID),
	FOREIGN KEY (CLI_ID)
	REFERENCES T_CLIENT(CLI_ID),
	FOREIGN KEY (PMT_CODE)
	REFERENCES T_MODE(PMT_CODE)
);

CREATE TABLE IF NOT EXISTS T_LIGNE_FACTURE(
	LIF_ID INT NOT NULL,
	FAC_ID INT,
	LIF_QTE NUMERIC,
	LIF_REMISE_POURCENT NUMERIC,
	LIF_REMISE_MONTANT NUMERIC(8,2),
	LIF_MONTANT NUMERIC(8,2),
	LIF_TAUX_TVA NUMERIC(8,2),
	PRIMARY KEY (LIF_ID),
	FOREIGN KEY (FAC_ID)
	REFERENCES T_FACTURE(FAC_ID)
);

CREATE TABLE IF NOT EXISTS T_TARIF(
	TRF_DATE_DEBUT DATE NOT NULL,
	TRF_TAUX_TAXES NUMERIC,
	TRF_PETIT_DEJEUNE NUMERIC,
	PRIMARY KEY (TRF_DATE_DEBUT)
);

CREATE TABLE IF NOT EXISTS T_CHAMBRE(
	CHB_ID INT NOT NULL,
	CHB_NUMERO SMALLINT,
	CHB_ETAGE CHAR(3),
	CHB_BAIN NUMERIC(1),
	CHB_DOUCHE NUMERIC(1),
	CHB_WC NUMERIC(1),
	CHB_COUCHAGE SMALLINT,
	CHB_POSTE_TEL CHAR(3),
	PRIMARY KEY (CHB_ID)
);

CREATE TABLE IF NOT EXISTS TJ_TRF_CHB(
	CHB_ID INT NOT NULL,
	TRF_DATE_DEBUT DATE,
	TRF_CHB_PRIX NUMERIC(8,2),
	UNIQUE (CHB_ID,TRF_DATE_DEBUT)
);

CREATE TABLE IF NOT EXISTS T_PLANNING(
	PLN_JOUR DATE NOT NULL,
	PRIMARY KEY (PLN_JOUR)
);

CREATE TABLE IF NOT EXISTS TJ_CHB_PLN_CLI(
	CHB_ID INT NOT NULL,
	PLN_JOUR DATE,
	CLI_ID INT,
	CHB_PLN_CLI_NB_PERS SMALLINT,
	CHB_PLN_CLI_RESERVE NUMERIC(1),
	CHB_PLN_CLI_OCCUE NUMERIC(1),
	UNIQUE (CHB_ID,PLN_JOUR),
	FOREIGN KEY (CHB_ID)
	REFERENCES T_CHAMBRE(CHB_ID),
	FOREIGN KEY (PLN_JOUR)
	REFERENCES T_PLANNING(PLN_JOUR),
	FOREIGN KEY (CLI_ID)
	REFERENCES T_CLIENT(CLI_ID)
);